language: python

python: 3.6

before_install:
  - python --version
  - pip install -U pip

install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  # Note: Build throws a warning here because conda isn't updated, but doing so causes a RemoveError.
  # Useful for debugging any issues with conda
  - conda info -a
  - conda env create --name microdf-env --file=environment.yml python=$TRAVIS_PYTHON_VERSION
  - conda activate microdf-env

script:
  - coverage run -m pytest -v

after_success:
  - codecov